### ISSUE TITLE
Error while calling uploadFile api.. Network Error

### ISSUE THREAD

**Issue by code-inhub** [code-inhub/MeChat#1]
Could not able to send Images to mongoDB
whenever trying to do so it results in server crash

**Comment by Vayras** [comment]
@code-inhub In your api call you have a return statement next to the api url , so I have fixed it by making sure it return a response

**Comment by code-inhub** [comment]
Thanks a lot for your contribution,
I appreciate you tried something helpful. But actually it is not solving the error.
The console is still showing : Error while calling uploadFile api
and server is getting crashed during this process.
This error will be shown when you will try sending some image from clip icon.
For any help you can contact me any time.

Console:
AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}
code
:
"ERR_NETWORK"
config
:
{transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}
message
:
"Network Error"
name
:
"AxiosError"
request
:
XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
stack
:
"AxiosError: Network Error\n at XMLHttpRequest.handleError (http://localhost:3000/static/js/bundle.js:66065:14)"
[[Prototype]]
:
Error
